#!/bin/bash

NAME=BUAA_Cat_Management_System
DIR=/root/2024BUAA_DB_Homework/backend
USER=root
GROUP=root
WORKERS=5
WORKER_CLASS=uvicorn.workers.UvicornWorker
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error

cd $DIR

# 激活 pipenv 环境
export PIPENV_PIPFILE=$DIR/Pipfile  # 指定 Pipfile 的位置
pipenv run which python >/dev/null 2>&1 || { echo "Pipenv environment not found. Exiting."; exit 1; }

# 启动 Gunicorn
exec pipenv run gunicorn app.main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
