"""add CASCADE DELETE to CatLocation

Revision ID: 7882c47ae3ad
Revises: a2e86c3348a8
Create Date: 2024-12-09 21:35:57.704024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7882c47ae3ad'
down_revision: Union[str, None] = 'a2e86c3348a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'latest_location_id')
    op.drop_index('ix_cat_latest_location_id', table_name='cat')
    op.create_foreign_key(None, 'catlocation', 'cat', ['cat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catlocation', type_='foreignkey')
    op.add_column('cat', sa.Column('latest_location_id', mysql.CHAR(length=32), nullable=True))
    op.create_index('ix_cat_latest_location_id', 'cat', ['latest_location_id'], unique=False)
    # ### end Alembic commands ###
