"""add CASCADE DELETE to Like table

Revision ID: a2e86c3348a8
Revises: b1453270dac5
Create Date: 2024-11-28 20:56:54.473456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2e86c3348a8'
down_revision: Union[str, None] = 'b1453270dac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_ibfk_2', 'like', type_='foreignkey')
    op.drop_constraint('like_ibfk_1', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_cat_id', 'post', ['cat_id'], unique=False)
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_ibfk_1', 'like', 'post', ['post_id'], ['id'])
    op.create_foreign_key('like_ibfk_2', 'like', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
